
const filterOptions = {

    // files categories
     filesCategory: [
      {
        value: 'Full info credit report, CS 600-700',
        label: 'Full info credit report, CS 600-700',
      },
      {
        value: 'Full info credit report, CS 700-800',
        label: 'Full info credit report, CS 700-800',
      },
      {
        value: 'Full info credit report, CS 800-850',
        label: 'Full info credit report, CS 800-850',
      },
      { value: 'Full info, CS 600-700', label: 'Full info, CS 600-700' },
      { value: 'Full info, CS 700-800', label: 'Full info, CS 700-800' },
      { value: 'Full info, CS 800-850', label: 'Full info, CS 800-850' },
      { value: 'Business fullz', label: 'Business fullz' },
      {
        value: 'Full info, cr bg file pdf cs 500-650',
        label: 'Full info, cr bg file pdf cs 500-650',
      },
      {
        value: 'Full info, cr bg file pdf cs 700-800',
        label: 'Full info, cr bg file pdf cs 700-800',
      },
      {
        value: 'Driver license (quality random)',
        label: 'Driver license (quality random)',
      },
      {
        value: 'Passport (quality random)',
        label: 'Passport (quality random)',
      },
      { value: 'ID (quality random)', label: 'ID (quality random)' },
      { value: 'DL with selfie', label: 'DL with selfie' },
      { value: 'ID with selfie', label: 'ID with selfie' },
      {
        value: 'Other documents (quality random)',
        label: 'Other documents (quality random)',
      },
      { value: 'Fullz with BG', label: 'Fullz with BG' },
      { value: 'Driver license FRONT', label: 'Driver license FRONT' },
      {
        value: 'Driver license FRONT_BACK',
        label: 'Driver license FRONT_BACK',
      },
      { value: 'Taxes W-forms', label: 'Taxes W-forms' },
    ],
//    all states
    state: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],

//   accounts categories
 accountsCategory: [
       { value: 'CHASE (Self-registered accounts)', label: 'CHASE (Self-registered accounts)' },
       { value: 'Chime (Self-registered accounts)', label: 'Chime (Self-registered accounts)' },
       { value: 'PayPal (Self-registered accounts)', label: 'PayPal (Self-registered accounts)' },
       { value: 'TD Bank (Self-registered accounts)', label: 'TD Bank (Self-registered accounts)' },
       { value: 'Capital One (Self-registered accounts)', label: 'Capital One (Self-registered accounts)' },
       { value: 'Marcus Bank (Self-registered accounts)', label: 'Marcus Bank (Self-registered accounts)' },
       { value: 'Citizens (Self-registered accounts)', label: 'Citizens (Self-registered accounts)' },
       { value: 'CEX.IO (Self-registered accounts)', label: 'CEX.IO (Self-registered accounts)' },
       { value: 'Current.com (Self-registered accounts)', label: 'Current.com (Self-registered accounts)' },
       { value: 'Сrypto wallet seller (Self-registered accounts)', label: 'Сrypto wallet seller (Self-registered accounts)' },
       { value: 'Moneylion (Self-registered accounts)', label: 'Moneylion (Self-registered accounts)' },
       { value: 'Bluebird bank account (Self-registered accounts)', label: 'Bluebird bank account (Self-registered accounts)' },
       { value: 'Bmoharris.com (Self-registered accounts)', label: 'Bmoharris.com (Self-registered accounts)' },
       { value: 'go2bank.com (Self-registered accounts)', label: 'go2bank.com (Self-registered accounts)' },
       { value: 'Key bank (Self-registered accounts)', label: 'Key bank (Self-registered accounts)' },
       { value: 'CashApp VCC not verified (Self-registered accounts)', label: 'CashApp VCC not verified (Self-registered accounts)' },
       { value: 'Nerdwallet.com (Self-registered accounts)', label: 'Nerdwallet.com (Self-registered accounts)' },
       { value: 'Schwab bank (Self-registered accounts)', label: 'Schwab bank (Self-registered accounts)' },
       { value: 'Dave bank (Self-registered accounts)', label: 'Dave bank (Self-registered accounts)' },
       { value: 'Regions (Self-registered accounts)', label: 'Regions (Self-registered accounts)' },
       { value: 'Found.com (Self-registered accounts)', label: 'Found.com (Self-registered accounts)' },
       { value: 'Coinbase (Self-registered accounts)', label: 'Coinbase (Self-registered accounts)' },
       { value: 'FNBO (Self-registered accounts)', label: 'FNBO (Self-registered accounts)' },
       { value: 'WalmartMoneyCard.com (Self-registered accounts)', label: 'WalmartMoneyCard.com (Self-registered accounts)' },
       { value: 'Taxes W-forms (accounts)', label: 'Taxes W-forms (accounts)' },
       { value: 'Square (Self-registered accounts)', label: 'Square (Self-registered accounts)' },
       { value: 'Venmo (Self-registered accounts)', label: 'Venmo (Self-registered accounts)' },
       { value: 'kraken.com (Self-registered accounts)', label: 'kraken.com (Self-registered accounts)' },
       { value: 'CoinEx (Self-registered accounts)', label: 'CoinEx (Self-registered accounts)' },
       { value: 'Bank of the west (Self-registered accounts)', label: 'Bank of the west (Self-registered accounts)' },
       { value: 'American Express (Self-registered accounts)', label: 'American Express (Self-registered accounts)' },
       { value: 'Winden bank (Self-registered accounts)', label: 'Winden bank (Self-registered accounts)' },
       { value: 'MT (Self-registered accounts)', label: 'MT (Self-registered accounts)' },
       { value: 'Grind24 (Self-registered accounts)', label: 'Grind24 (Self-registered accounts)' },
       { value: 'Stash (Self-registered accounts)', label: 'Stash (Self-registered accounts)' },
       { value: 'Spendwell Bank (Self-registered accounts)', label: 'Spendwell Bank (Self-registered accounts)' },
       { value: 'PayActiv Bank (Self-registered accounts)', label: 'PayActiv Bank (Self-registered accounts)' },
       { value: 'H-E-B Debit (Self-registered accounts)', label: 'H-E-B Debit (Self-registered accounts)' },
       { value: 'Barclays bank (Self-registered accounts)', label: 'Barclays bank (Self-registered accounts)' },
       { value: 'TD Ameritrade (Self-registered accounts)', label: 'TD Ameritrade (Self-registered accounts)' },
       { value: 'Fidelity bloom (Self-registered accounts)', label: 'Fidelity bloom (Self-registered accounts)' },
       { value: 'Twig (Self-registered accounts)', label: 'Twig (Self-registered accounts)' },
       { value: 'Maza (Self-registered accounts)', label: 'Maza (Self-registered accounts)' },
       { value: 'Mana Finance (Self-registered accounts)', label: 'Mana Finance (Self-registered accounts)' },
       { value: 'First Merchants Bank (Self-registered accounts)', label: 'First Merchants Bank (Self-registered accounts)' },
       { value: 'Others', label: 'Others' },


      
    ],

    // cards level
    cardsLevel: [

    { value: 'CLASSIC ', label: 'CLASSIC ' },
    { value: 'PREPAID  ', label: 'PREPAID  ' },
    { value: 'PLATINUM ', label: 'PLATINUM ' },
    { value: 'PLATINUM  ', label: 'PLATINUM  ' },
    { value: 'PERSONAL  ', label: 'PERSONAL ' },
    { value: 'GOLD  ', label: 'GOLD ' },
    { value: 'PREPAID RELOADABLE ', label: 'PREPAID RELOADABLE ' },
    { value: 'GIFT  ', label: 'GIFT ' },
    { value: 'WORLD  ', label: 'WORLD  ' },
    { value: 'BUSINESS  ', label: 'BUSINESS ' },
    { value: 'ELECTRON ', label: 'ELECTRON ' },
    { value: 'WORLD ELITE ( ', label: 'WORLD ELITE  ' },
    { value: 'ENHANCED  ', label: 'ENHANCED ' },
    { value: 'PREPAID ELECTRON   ', label: 'PREPAID ELECTRON  ' },
    { value: 'CONSUMER CHARGE ', label: 'CONSUMER CHARGE  ' },
    { value: 'PREPAID GOVERNMENT', label: 'PREPAID GOVERNMENT  ' },
    { value: 'PERSONAL REVOLVE ', label: 'PERSONAL REVOLVE ' },
    { value: 'CONSUMER LENDING  ', label: 'CONSUMER LENDING  ' },
    { value: 'SIGNATURE  ', label: 'SIGNATURE (1366) ' },
    { value: 'REWARDS  ', label: 'REWARDS  ' },
    { value: 'CCSG LENDING  ', label: 'CCSG LENDING  ' },
    { value: 'COMPANY  ', label: 'COMPANY  ' },
    { value: 'PREPAID PAYROLL ', label: 'PREPAID PAYROLL ' },
    { value: 'OTHERS ', label: 'OTHERS' },
    
    ],
    // cards 
    cardsClass : [
    { value: 'DEBIT ', label: 'DEBIT ' },
    { value: 'CREDIT ', label: 'CREDIT ' },
    { value: 'CHARGE CARD ', label: 'CHARGE CARD ' },


    ],
    // CARDS TYPE 
    cardsType: [
     { value: 'VISA', label: 'VISA' },
    { value: 'MASTERCARD', label: 'MASTERCARD' },
    { value: 'AMERICAN EXPRESS', label: 'AMERICAN EXPRESS' },
    { value: 'DISCOVER ', label: 'DISCOVER ' },
    { value: 'MAESTRO ', label: 'MAESTRO ' },
    { value: 'VISA/DANKORT', label: 'VISA/DANKORT' },
    { value: 'UATP ', label: 'UATP ' },
    { value: 'EBT ', label: 'EBT' },
    { value: 'ELO ', label: 'ELO ' },
    { value: 'RUPAY ', label: 'RUPAY ' },
    { value: 'PRIVATE LABEL ', label: 'PRIVATE LABEL ' },
    { value: 'LOCAL BRAND ', label: 'LOCAL BRAND ' },

    ],
    // ssn/dob base
    ssnBase:[
     { value: 'USA Full info, DL', label: 'USA Full info, DL' },
     { value: 'BIG UPDATE 0.55$', label: 'BIG UPDATE 0.55$' },
     { value: 'Federal base USA 2$', label: 'Federal base USA 2$' },
     { value: 'Private fresh fullz', label: 'Private fresh fullz' },
     { value: 'USA BIG DATA', label: 'USA BIG DATA' },
     { value: 'USA Fresh, DL', label: 'USA Fresh, DL' },
     { value: 'USA Full DL(no EXP)', label: 'USA Full DL(no EXP)' },
     { value: 'USA Full info V', label: 'USA Full info V' },
     { value: 'USA FULL INFO, Credit score', label: 'USA FULL INFO, Credit score' },
     { value: 'USA Full info, DL, NEW', label: 'USA Full info, DL, NEW' },
     { value: 'USA TOP BASE, DL', label: 'USA TOP BASE, DL' },


    ],

}


export default filterOptions;